name: Deploy to Gandi via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy files to Gandi via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: sftp.dc2.gpaas.net
          port: 22

          # PASSWORD instead of ssh_private_key
          password: ${{ secrets.SFTP_PASSWORD }}
          sftp_only: true
          # everything in the repo root (your index.html, css, js)
          local_path: './*'
          # ⬇️ the remote path from FileZilla
          remote_path: '/lamp0/web/vhosts/flowerseed.io/htdocs'
          # optional: don’t upload git + workflow files
          rsyncArgs: '--exclude=.git --exclude=.github'
          sftpArgs: '-o ConnectTimeout=5'
